FROM tensorflow/tensorflow:1.14.0-gpu-py3

ADD ./requirements.base.txt /code/
ADD ./requirements.txt /code/

WORKDIR /code

RUN apt-get update \
    && DEBIAN_FRONTEND="noninteractive" apt-get install -y build-essential mpich libpq-dev python3-opencv\
    && pip install -r requirements.txt
